os:
  - linux
  - windows
  
  


language: python
python:
  - '3.5'
  - '3.6'
  - "pypy3.5"


before_install:

      - sudo  add-apt-repository  -y ppa:otto-kesselgulasch/gimp
      - sudo apt-get update -qq
      - sudo apt install -y libgmic-dev cmake libboost-all-dev libeigen3-dev   python-dev python3-dev catch python3-pip  python3-numpy
      - sudo apt-get install git build-essential libgimp2.0-dev libcv-dev libopencv-dev  libhighgui-dev libcurl4-openssl-dev libfftw3-dev 

#      - wget https://gmic.eu/files/windows/gmic_lib_win64.zip
#      - mkdir c:\\gmic
#      - 7z e -oc:\\gmic
      
      
# command to run tests
install:
  - pip install coverage
  - pip install   -r requirements.txt
  - python setup.py -q install
script: coverage run  setup.py -q test

after_success:
- coveralls
