version: 1.0.{build}
image:
- Visual Studio 2017
- Ubuntu1804

environment:

  matrix:

    # For Python versions available on Appveyor, see
    # https://www.appveyor.com/docs/windows-images-software/#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.

    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

#matrix:
 # exclude:
  #- image: Ubuntu1804
   # - PYTHON: "C:\\Python27"
    #- PYTHON: "C:\\Python36"


install:

  - cmd: curl -o c:\\gmic_lib_win64.zip  https://gmic.eu/files/windows/gmic_lib_win64.zip
  - cmd: 7z  e -oc:\\gmic  c:\\gmic_lib_win64.zip
  - sh: sudo  add-apt-repository  -y ppa:otto-kesselgulasch/gimp
  - sh: sudo apt-get update -qq
  - sh: sudo apt install -y libgmic-dev cmake libboost-all-dev libeigen3-dev   python-dev python3-dev catch python3-pip  python3-numpy
  - sh: sudo apt-get install -y git build-essential libgimp2.0-dev libcv-dev libopencv-dev  libhighgui-dev libcurl4-openssl-dev libfftw3-dev 





build_script:
- sh: >-
    python  -m pip install -e .
    
    python  -m pip install -e .
- cmd: >-
    %PYTHON%\\python  -m pip install -e .   --include-dirs c:\\gmic   --library-dirs c:\\gmic  



 
 
test_script:
- sh: >-
    python setup.py test

    python3 setup.py test
- cmd: >-
    "%PYTHON%\\python setup.py test"

    
    
artifacts:


  - path: '**\*.whl'
deploy:
- provider: BinTray
  username: cedspam
  api_key:
    secure: ZGSL5wez3hps3RuZ1eJ2iIA8qxTKcjyUqS94dLrWJu3k35RX9KRsVpP3zagnAajr
  subject: cedspam
  repo: gmicpy
  package: gmicpy
  publish: true
  explode: false
before_deploy:
  - sh: >-
      python setup.py bdist_wheel

      python3 setup.py bdist_wheel
  - cmd: >-
      "%PYTHON%\\python setup.py bdist_wheel"
