version: 2
jobs:
  build:
    working_directory: ~/gmicpy
    docker:
        - image: circleci/python:latest
       
    steps:
      - checkout
      - run:
          name: add repository
          command: 'sudo apt-get install -y software-properties-common'
      - run:
          name: add repository
          command: 'sudo  add-apt-repository  -y ppa:otto-kesselgulasch/gimp'
      - run:
          name: install dev packages
          command: 'sudo apt install -y libgmic-dev libboost-all-dev  python-dev python3-dev pybind11-dev '
      - run:
          name: install requirements
          command: 'pip3 install  --user  -r requirements.txt '
      - run:
          name: compile
          command: 'python setup.py -q install  --user'
      - run:
          name: bdist
          command: 'python setup.py -q bdist_wheel'   
      - store_artifacts:
          path: ~/gmicpy/dist
          
          
  test:
    working_directory: ~/gmicpy
    docker:
        - image: circleci/python:latest
       
    steps:

      - run:
          name: add repository
          command: 'python setup.py -q test'  
          
workflows:
 version: 2
 Example_Workflow:
   jobs:
     - build
     - test:
         requires:
           - build
      
